### ISSUE TITLE
Fix bug in `test_main` module

### ISSUE THREAD

**Issue by sigma1326** [tensorops/TransformerX#11]
When running running `test_main` module, I encountered this error:

`test_main.py:42: in <module>
    encoder_blk = TransformerEncoderBlock(24, 24, 24, 24, norm_shape, 48, 8, 0.5)
E   TypeError: TransformerEncoderBlock.__init__() takes from 6 to 7 positional arguments but 9 were given`

It seems invalid and needs to be fixed.

**Comment by soran-ghaderi** [comment]
It is due to the extra arguments given. Right now the code works fine for self-attention.
I will modify the examples, however, the layers should support cross-attention as well which we should modify it later.
